In [ ]:
import numpy as np
A = np.array([[0, 1], [2, 3], [4, 5]])
B = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
result = np.dot(A, B)
print(result)
max_value = np.max(result)
print(max_value)

[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
47
